## Append samples of your project ##
resources:
- v1alpha1_kdexapp.yaml
- v1alpha1_kdexhost.yaml
- v1alpha1_kdexhostcontroller.yaml
- v1alpha1_kdexpagearchetype.yaml
- v1alpha1_kdexpagebinding.yaml
- v1alpha1_kdexpagefooter.yaml
- v1alpha1_kdexpageheader.yaml
- v1alpha1_kdexpagenavigation.yaml
- v1alpha1_kdexscriptlibrary.yaml
- v1alpha1_kdextheme.yaml
- v1alpha1_kdextranslation.yaml
- v1alpha1_kdexhostpackagereferences.yaml
- v1alpha1_kdexclusterapp.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
