apiVersion: kdex.dev/v1alpha1
kind: KDexClusterApp
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexclusterapp-sample
spec:
  customElements:
  - name: my-app-element
  packageReference:
    name: my-app
    version: 1.0.0
