apiVersion: kdex.dev/v1alpha1
kind: KDexHost
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexhost-sample
spec:
  brandName: KDex Sample Site
  defaultLang: en
  defaultThemeRef:
    kind: KDexTheme
    name: kdextheme-sample
  organization: KDex Tech Inc.
  modulePolicy: Loose
  routing:
    domains:
    - site-a.test
