apiVersion: kdex.dev/v1alpha1
kind: KDexRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexrolebinding-sample
spec: # TODO(user): Add fields here
