apiVersion: kdex.dev/v1alpha1
kind: KDexPageBinding
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexpagebinding-sample
spec:
  basePath: /my-app-page
  contentEntries:
    - appRef:
        kind: KDexApp
        name: my-app
      customElementName: my-element
      slot: main
    - rawHTML: |
        <p>Hello world!</p>
      slot: column-2
  hostRef:
    name: sample-host
  label: My Page
  navigationHints:
    weight: 1
  overrideFooterRef:
    kind: KDexPageFooter
    name: generic-footer
  overrideHeaderRef:
    kind: KDexPageHeader
    name: generic-header
  overrideMainNavigationRef:
    kind: KDexPageNavigation
    name: generic-navigation
  pageArchetypeRef:
    kind: KDexPageArchetype
    name: generic-page