apiVersion: kdex.dev/v1alpha1
kind: KDexApp
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexapp-sample
spec:
  customElements:
    - description: "A custom element"
      name: "my-element"
  packageReference:
    name: "@kdex-samples/simple-form"
    version: "1.0.0"