apiVersion: kdex.dev/v1alpha1
kind: KDexClusterUtilityPage
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexclusterutilitypage-sample
spec:
  contentEntries:
  - rawHTML: |
      <div class="container">
          <h1>{{ l10n "error.title" .BrandName }}</h1>

          <strong>{{ .Extra.ErrorCode }}</strong>
          <p class="message">{{l10n "error.message" .Extra.ErrorCode}}</p>

          <div class="footer">
              <p>{{l10n "announcement.organization" .Organization}}</p>
          </div>
      </div>
    slot: main
  pageArchetypeRef:
    kind: KDexClusterPageArchetype
    name: kdexclusterpagearchetype-sample
  type: Error
