apiVersion: kdex.dev/v1alpha1
kind: KDexPageFooter
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexpagefooter-sample
spec:
  content: |
    <small>&copy; {{ .Date.Year() }} {{ .Organization }}. All Rights Reserved.</small>