apiVersion: kdex.dev/v1alpha1
kind: KDexPageHeader
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexpageheader-sample
spec:
  content: |
    <a class="logo" href="#">{{ .Title }}</a>