apiVersion: kdex.dev/v1alpha1
kind: KDexTranslation
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdextranslation-sample
spec:
  translations:
  - keysAndValues:
      name: Name
    lang: en
  - keysAndValues:
      name: Nom
    lang: fr
