apiVersion: kdex.dev/v1alpha1
kind: KDexClusterTheme
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexclustertheme-sample
spec:
  assets:
  - attributes:
      media: (width < 500px)
    style: |
      p {
        color: blue;
        background-color: yellow;
      }
  - style: |
      p {
        color: white;
        background-color: blue;
        padding: 5px;
        border: 1px solid black;
      }
  - attributes:
      rel: theme
    linkHref: https://cdn.tailwindcss.com
