apiVersion: kdex.dev/v1alpha1
kind: KDexScriptLibrary
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexscriptlibrary-sample
spec:
  scripts:
  - attributes:
      type: text/javascript
    footScript: true
    script: |
      console.log('hello');
  - attributes:
      type: module
    scriptSrc: /my-script.js
