apiVersion: kdex.dev/v1alpha1
kind: KDexPageNavigation
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexpagenavigation-sample
spec:
  content: |
    {{- define "menu" -}}
      <ul>
        {{- range $label, $value := . }}
          <li>
            {{- if ($value.Path != "") -}}
              <a href="{{ $value.Path }}">{{ $label }}</a>
            {{- else -}}
              <span>{{ $label }}</span>
            {{- end -}}
            {{- if ($value.Children != nil) -}}
              {{- template "menu" $value.Children -}}
            {{- end -}}
          </li>
        {{- end -}}
      </ul>
    {{- end -}}
    {{- template "menu" .MenuEntries -}}