apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageHeader
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexclusterpageheader-sample
spec:
  content: |
    <a class="logo" href="#">{{ .Title }}</a>
