apiVersion: kdex.dev/v1alpha1
kind: KDexPageArchetype
metadata:
  labels:
    app.kubernetes.io/name: kdex-crds
    app.kubernetes.io/managed-by: kustomize
  name: kdexpagearchetype-sample
spec:
  content: |
    <!DOCTYPE html>
    <html lang="{{ .Language }}">
      <head>
        {{ .Meta }}
        <title>{{ .Title }}<title>
        {{ .Theme }}
        {{ .HeadScript }}
      </head>
      <body>
        <header>
          {{ .Header }}
        </header>
        <nav>
          {{ .Navigation["main"] }}
        </nav>
        <main>
          {{ .Content["main"] }}
        </main>
        <footer>
          {{ .Footer }}
        </footer>
        {{ .FootScript }}
      </body>
    </html>
  defaultFooterRef:
    name: kdexpagefooter-sample
  defaultHeaderRef:
    name: kdexpageheader-sample
  defaultMainNavigationRef:
    name: kdexpagenavigation-sample
  defaultThemeRef:
    name: kdextheme-sample